# SPDX-License-Identifier GPL-2.0+
---
topdir_path: "/dev/null"

hosts_type_generic: true
hosts_type_fs: false
hosts_type_block: false

kdevops_hosts_template: "hosts.in"
kdevops_playbooks_dir: "/dev/null"
kdevops_genhosts_templates_dir: "/dev/null"
kdevops_hosts_prefix: "kdevops"
kdevops_python_interpreter: "/usr/bin/python3"
kdevops_python_old_interpreter: "/usr/bin/python2"
kdevops_baseline_and_dev: false
kdevops_playbooks_dir_full_path: "/dev/null"
kdevops_hosts_template_full_path: "/dev/null"

kdevops_workflows_dedicated_workflow: false
kdevops_workflow_enable_fstests: false
kdevops_workflow_enable_blktests: false
kdevops_workflow_enable_selftests: false

kdevops_workflow_enable_cxl: false
kdevops_workflow_enable_pynfs: false
kdevops_workflow_enable_gitr: false
kdevops_workflow_enable_ltp: false
kdevops_workflow_enable_nfstest: false
kdevops_workflow_enable_sysbench: false
kdevops_workflow_enable_fio_tests: false
kdevops_workflow_enable_mmtests: false
workflows_reboot_limit: false

is_fstests: false
fstests_fstyp: "bogus"
fs_config_role_path: "/dev/null"
fs_config_data: "[section_1]"

kdevops_nfsd_enable: false
kdevops_loopback_nfs_enable: false
kdevops_smbd_enable: false
kdevops_krb5_enable: false
kdevops_enable_iscsi: false

bootlinux_builder: false
