---
- name: Check if unattended-upgrades is installed
  command: dpkg-query -W -f='${Status}' unattended-upgrades
  register: unattended_upgrade_status
  ignore_errors: true
  changed_when: false
  tags: firstconfig

- name: Set fact if unattended-upgrades is installed
  set_fact:
    unattended_upgrades_installed: "{{ 'install ok installed' in unattended_upgrade_status.stdout }}"
  when:
    - kdevops_enable_guestfs|bool

- name: Verify unattended-upgrades is not installed
  fail:
    msg: |
      The unattended-upgrades package is installed on the base image, this
      can cause tons of issues with CIs. Fix this by running the following
      commands:

      make cleancache
      make bringup
  when:
    - kdevops_enable_guestfs|bool
    - unattended_upgrades_installed|bool
  tags: firstconfig

- name: Stop and disable unattended-upgrades related services
  become: true
  become_flags: "su - -c"
  become_method: sudo
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
    daemon_reload: true
  loop:
    - unattended-upgrades
    - apt-daily.service
    - apt-daily.timer
    - apt-daily-upgrade.service
    - apt-daily-upgrade.timer
    - systemd-networkd-wait-online.service
  ignore_errors: true
  tags: firstconfig

- name: Update apt cache accepting release info changes
  become: true
  become_method: sudo
  ansible.builtin.command:
    cmd: apt-get update --allow-releaseinfo-change
  changed_when: false
  ignore_errors: true
  tags: firstconfig

- name: Upgrade Packages
  become: true
  become_method: sudo
  ansible.builtin.apt:
    update_cache: false
    upgrade: "yes"
    lock_timeout: 120
  register: apt_upgrade
  until: apt_upgrade is success
  retries: 5
  delay: 60
  tags: firstconfig

- name: Remove unattended-upgrades package in case upgrade installed it
  become: true
  become_flags: "su - -c"
  become_method: sudo
  apt:
    name: unattended-upgrades
    state: absent
  register: removal_result
  retries: 20
  delay: 30
  until: removal_result is not failed
  tags: firstconfig

- name: Remove optional unattended-upgrades configuration files if they exist
  become: true
  become_flags: "su - -c"
  become_method: sudo
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/apt/apt.conf.d/20auto-upgrades
    - /etc/apt/apt.conf.d/02periodic
    - /etc/apt/apt.conf.d/50unattended-upgrades
    - /etc/apt/apt.conf.d/52unattended-upgrades-local
  ignore_errors: true
  tags: firstconfig

- name: Stop and disable unattended-upgrades related services
  become: true
  become_flags: "su - -c"
  become_method: sudo
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
    daemon_reload: true
  loop:
    - unattended-upgrades
    - apt-daily.service
    - apt-daily.timer
    - apt-daily-upgrade.service
    - apt-daily-upgrade.timer
    - systemd-networkd-wait-online.service
  ignore_errors: true
  tags: firstconfig

- name: Allow for distro source change / upgrade
  become: true
  become_flags: "su - -c"
  become_method: sudo
  command: "apt-get update  --allow-releaseinfo-change -o Acquire::Check-Valid-Until=false -o Acquire::Check-Date=false -o Acquire::AllowInsecureRepositories=true
    -o Acquire::MaxDate=10"
  register: release_info_changed
  changed_when: release_info_changed.rc == 0
  tags: ["apt", "release-info-change"]
  when:
    - devconfig_try_upgrade|bool

- name: Check for UNAVAIL in /etc/nsswitch.conf hosts line
  ansible.builtin.shell: grep -E '^hosts:.*UNAVAIL' /etc/nsswitch.conf
  register: nsswitch_check
  changed_when: false
  failed_when: false
  when:
    - distro_debian_has_hop1_sources|bool
    - guestfs_copy_sources_from_host_to_guest|bool

- name: Write custom nsswitch.conf for hop1 mirror heuristic
  become: true
  become_flags: "su - -c"
  become_method: sudo
  ansible.builtin.copy:
    content: |
      # kdevops generated /etc/nsswitch.conf
      passwd:         files
      group:          files
      shadow:         files
      gshadow:        files
      hosts:          files myhostname resolve dns
      networks:       files
      protocols:      db files
      services:       db files
      ethers:         db files
      rpc:            db files
      netgroup:       nis
    dest: /etc/nsswitch.conf
    owner: root
    group: root
    mode: "0644"
  when:
    - distro_debian_has_hop1_sources|bool
    - guestfs_copy_sources_from_host_to_guest|bool
    - nsswitch_check.rc == 0

- name: Configure APT to ignore `Valid-Until` timestamps on the host
  delegate_to: localhost
  run_once: true
  become: true
  become_method: sudo
  copy:
    content: |
      Acquire::Check-Valid-Until "false";
      Acquire::Check-Date "false";
      Acquire::AllowInsecureRepositories "true";
      Acquire::MaxDate "10";
    dest: /etc/apt/apt.conf.d/99ignore-release-date
  when:
    - distro_debian_has_hop1_sources|bool
    - guestfs_copy_sources_from_host_to_guest|bool

- name: Configure APT to ignore `Valid-Until` timestamps on the target node
  become: true
  become_method: sudo
  copy:
    content: |
      Acquire::Check-Valid-Until "false";
      Acquire::Check-Date "false";
      Acquire::AllowInsecureRepositories "true";
      Acquire::MaxDate "10";
    dest: /etc/apt/apt.conf.d/99ignore-release-date
  when:
    - distro_debian_has_hop1_sources|bool
    - guestfs_copy_sources_from_host_to_guest|bool

- name: Ensure we make Valid-Until trick take effect on host
  delegate_to: localhost
  run_once: true
  become: true
  become_method: sudo
  apt:
    update_cache: true
  when:
    - distro_debian_has_hop1_sources|bool
    - guestfs_copy_sources_from_host_to_guest|bool

- name: Ensure we make Valid-Until trick take effect on target node
  become: true
  become_method: sudo
  become_flags: "su - -c"
  apt:
    update_cache: true
  when:
    - distro_debian_has_hop1_sources|bool
    - guestfs_copy_sources_from_host_to_guest|bool

- name: Update apt cache and do dist-upgrade
  become: true
  become_method: sudo
  apt:
    update_cache: true
    upgrade: full
  tags: ["apt", "cache"]
  when:
    - devconfig_try_upgrade|bool

- name: Reboot system to make the new kernel and modules take effect
  become: true
  become_method: sudo
  reboot:
  when:
    - devconfig_try_upgrade|bool

- name: Install our generic dependencies
  become: true
  become_method: sudo
  apt:
    name:
      - grub2
      - nvme-cli
      - ssh
      - bison
      - flex
      - libelf-dev
      - libncurses-dev
      - screen
      - git
      - e2fsprogs
      - xfsprogs
      - btrfs-progs
      - lvm2
      - gcc
      - make
      - gawk
      - bc
      - dump
      - indent
      - libtool
      - psmisc
      - sed
      - vim
      - fio
      - libaio-dev
      - snmpd
      - snmp
      - trace-cmd
      - linux-perf
    state: present
    update_cache: true
  tags: ["kdevops", "deps"]
  when:
    - devconfig_try_install_kdevtools|bool

- name: Set up snmp
  become: true
  become_method: sudo
  template:
    src: snmpd.conf
    dest: /etc/snmp/snmpd.conf
  when:
    - devconfig_try_install_kdevtools|bool
  tags: snmpd

- name: Enable snmpd service
  become: true
  become_method: sudo
  systemd:
    name: snmpd
    enabled: true
    masked: false
  tags: snmpd
  when:
    - devconfig_try_install_kdevtools|bool

- name: Start snmpd service
  become: true
  become_method: sudo
  systemd:
    name: snmpd
    state: restarted
  tags: snmpd
  when:
    - devconfig_try_install_kdevtools|bool

- name: Install and sets up kdump
  become: true
  become_method: sudo
  apt:
    name:
      - kdump-tools
  when:
    - devconfig_try_install_kdevtools|bool
  tags: kdump

- name: Install systemd-journal-remote
  become: true
  become_method: sudo
  apt:
    name:
      - systemd-journal-remote
    update_cache: true
  when:
    - devconfig_enable_systemd_journal_remote|bool
  tags: journal

- name: Install systemd-timesyncd
  become: true
  become_method: sudo
  apt:
    name:
      - systemd-timesyncd
  when:
    - devconfig_enable_systemd_timesyncd|bool
  tags: timesyncd
