---
- name: Upgrade Packages
  become: yes
  become_method: sudo
  ansible.builtin.apt:
    upgrade: full
  tags: firstconfig

- name: Remove unattended-upgrades package
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  apt:
    name: unattended-upgrades
    state: absent
  register: removal_result
  retries: 20
  delay: 30
  until: removal_result is not failed

- name: Remove optional unattended-upgrades configuration files if they exist
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/apt/apt.conf.d/20auto-upgrades
    - /etc/apt/apt.conf.d/02periodic
    - /etc/apt/apt.conf.d/50unattended-upgrades
    - /etc/apt/apt.conf.d/52unattended-upgrades-local
  ignore_errors: yes

- name: Stop and disable unattended-upgrades related services
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
    daemon_reload: yes
  loop:
    - unattended-upgrades
    - apt-daily.service
    - apt-daily.timer
    - apt-daily-upgrade.service
    - apt-daily-upgrade.timer
    - systemd-networkd-wait-online.service
  ignore_errors: yes

- name: Allow for distro source change / upgrade
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  command: "apt-get update  --allow-releaseinfo-change -o Acquire::Check-Valid-Until=false -o Acquire::Check-Date=false -o Acquire::AllowInsecureRepositories=true -o Acquire::MaxDate=10"
  register: release_info_changed
  changed_when: release_info_changed.rc == 0
  tags: [ 'apt', 'release-info-change' ]
  when:
    - devconfig_try_upgrade|bool

- name: Check for UNAVAIL in /etc/nsswitch.conf hosts line
  ansible.builtin.shell: grep -E '^hosts:.*UNAVAIL' /etc/nsswitch.conf
  register: nsswitch_check
  changed_when: false
  failed_when: false
  when:
    - distro_debian_has_hop1_sources|bool
    - guestfs_copy_sources_from_host_to_guest|bool

- name: Write custom nsswitch.conf for hop1 mirror heuristic
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  ansible.builtin.copy:
    content: |
      # kdevops generated /etc/nsswitch.conf
      passwd:         files
      group:          files
      shadow:         files
      gshadow:        files
      hosts:          files myhostname resolve dns
      networks:       files
      protocols:      db files
      services:       db files
      ethers:         db files
      rpc:            db files
      netgroup:       nis
    dest: /etc/nsswitch.conf
    owner: root
    group: root
    mode: '0644'
  when:
    - distro_debian_has_hop1_sources|bool
    - guestfs_copy_sources_from_host_to_guest|bool
    - nsswitch_check.rc == 0

- name: Configure APT to ignore `Valid-Until` timestamps on the host
  delegate_to: localhost
  run_once: true
  become: yes
  become_method: sudo
  copy:
    content: |
      Acquire::Check-Valid-Until "false";
      Acquire::Check-Date "false";
      Acquire::AllowInsecureRepositories "true";
      Acquire::MaxDate "10";
    dest: /etc/apt/apt.conf.d/99ignore-release-date
  when:
    - distro_debian_has_hop1_sources|bool
    - guestfs_copy_sources_from_host_to_guest|bool

- name: Configure APT to ignore `Valid-Until` timestamps on the target node
  become: yes
  become_method: sudo
  copy:
    content: |
      Acquire::Check-Valid-Until "false";
      Acquire::Check-Date "false";
      Acquire::AllowInsecureRepositories "true";
      Acquire::MaxDate "10";
    dest: /etc/apt/apt.conf.d/99ignore-release-date
  when:
    - distro_debian_has_hop1_sources|bool
    - guestfs_copy_sources_from_host_to_guest|bool

- name: Ensure we make Valid-Until trick take effect on host
  delegate_to: localhost
  run_once: true
  become: yes
  become_method: sudo
  apt:
    update_cache: yes
  when:
    - distro_debian_has_hop1_sources|bool
    - guestfs_copy_sources_from_host_to_guest|bool

- name: Ensure we make Valid-Until trick take effect on target node
  become: yes
  become_method: sudo
  become_flags: 'su - -c'
  apt:
    update_cache: yes
  when:
    - distro_debian_has_hop1_sources|bool
    - guestfs_copy_sources_from_host_to_guest|bool

- name: Update apt cache and do dist-upgrade
  become: yes
  become_method: sudo
  apt:
    update_cache: yes
    upgrade: full
  tags: [ 'apt', 'cache' ]
  when:
    - devconfig_try_upgrade|bool

- name: Reboot system to make the new kernel and modules take effect
  become: yes
  become_method: sudo
  reboot:
  when:
    - devconfig_try_upgrade|bool

- name: Install our generic dependencies
  become: yes
  become_method: sudo
  apt:
    name:
      - grub2
      - nvme-cli
      - ssh
      - bison
      - flex
      - libelf-dev
      - libncurses-dev
      - screen
      - git
      - e2fsprogs
      - xfsprogs
      - btrfs-progs
      - lvm2
      - gcc
      - make
      - gawk
      - bc
      - dump
      - indent
      - libtool
      - psmisc
      - sed
      - vim
      - fio
      - libaio-dev
      - snmpd
      - snmp
      - trace-cmd
      - linux-perf
    state: present
    update_cache: yes
  tags: [ 'kdevops', 'deps' ]
  when:
    - devconfig_try_install_kdevtools|bool

- name: Set up snmp
  become: yes
  become_method: sudo
  template:
    src: snmpd.conf
    dest: /etc/snmp/snmpd.conf
  when:
    - devconfig_try_install_kdevtools|bool
  tags: snmpd

- name: Enable snmpd service
  become: yes
  become_method: sudo
  systemd:
    name: snmpd
    enabled: yes
    masked: no
  tags: snmpd
  when:
    - devconfig_try_install_kdevtools|bool

- name: Start snmpd service
  become: yes
  become_method: sudo
  systemd:
    name: snmpd
    state: restarted
  tags: snmpd
  when:
    - devconfig_try_install_kdevtools|bool

- name: Install and sets up kdump
  become: yes
  become_method: sudo
  apt:
    name:
      - kdump-tools
  when:
    - devconfig_try_install_kdevtools|bool
  tags: kdump

- name: Install systemd-journal-remote
  become: yes
  become_method: sudo
  apt:
    name:
      - systemd-journal-remote
    update_cache: yes
  when:
    - devconfig_enable_systemd_journal_remote|bool
  tags: journal

- name: Install systemd-timesyncd
  become: yes
  become_method: sudo
  apt:
    name:
      - systemd-timesyncd
  when:
    - devconfig_enable_systemd_timesyncd|bool
  tags: timesyncd
