---
- name: Create a new LVM partition
  become: true
  become_flags: "su - -c"
  become_method: ansible.builtin.sudo
  delegate_to: "{{ server_host }}"
  community.general.lvol:
    vg: exports
    lv: "{{ export_volname }}"
    size: "{{ export_size }}"

- name: Format new volume for {{ export_fstype }}
  become: true
  become_flags: "su - -c"
  become_method: ansible.builtin.sudo
  delegate_to: "{{ server_host }}"
  community.general.filesystem:
    fstype: "{{ export_fstype }}"
    dev: "/dev/exports/{{ export_volname }}"

- name: Mount volume under {{ nfsd_export_path }}
  become: true
  become_flags: "su - -c"
  become_method: ansible.builtin.sudo
  delegate_to: "{{ server_host }}"
  throttle: 1 # running this in parallel can clobber fstab changes
  ansible.posix.mount:
    path: "{{ nfsd_export_path }}/{{ export_volname }}"
    src: "/dev/exports/{{ export_volname }}"
    fstype: "{{ export_fstype }}"
    state: mounted
