---
- name: Install fio for SUSE
  ansible.builtin.package:
    name:
      - fio
      - python3
      - git
    state: present
  become: true

- name: Install graphing dependencies for SUSE
  ansible.builtin.package:
    name:
      - python3-pip
      - python3-pandas
      - python3-matplotlib
      - python3-seaborn
      - python3-numpy
    state: present
  become: true
  when: fio_tests_enable_graphing is defined and fio_tests_enable_graphing
