---
- name: Enable the CodeReady repo
  ansible.builtin.include_role:
    name: codereadyrepo

- name: Enable installation of packages from EPEL
  ansible.builtin.include_role:
    name: epel-release
  when:
    - ansible_distribution != "Fedora"

- name: Install build dependencies for fstests
  become: true
  become_method: sudo
  yum:
    update_cache: true
    name: "{{ packages }}"
  retries: 3
  delay: 5
  register: result
  until: result is succeeded
  vars:
    packages:
      - bison
      - flex
      - git-core
      - automake
      - gcc
      - libuuid
      - libuuid-devel
      - quota
      - make
      - xfsprogs
      - xfsprogs-devel
      - xfsdump
      - e2fsprogs
      - gawk
      - util-linux
      - uuid
      - libuuid-devel
      - acl
      - bc
      - dump
      - indent
      - libtool
      - lvm2
      - psmisc
      - sed
      - libacl
      - libacl-devel
      - libaio
      - libaio-devel
      - attr
      - libattr-devel
      - openssl-devel
      - ca-certificates
      - libcap
      - gdbm-libs
      - fio
      - dbench
      - e2fsprogs-devel
      - libblkid-devel
      - libzstd-devel
      - libudev-devel
      - python3-devel
      - lzo-devel
      - parted
      - nfs-utils
      - liburing-devel
      - cifs-utils
      - duperemove
      - gettext
      - ncurses
      - ncurses-devel

- name: Install xfsprogs-xfs_scrub
  become: true
  become_method: sudo
  yum:
    update_cache: true
    name: "{{ packages }}"
  retries: 3
  delay: 5
  register: result
  until: result is succeeded
  vars:
    packages:
      - xfsprogs-xfs_scrub
  when:
    - (ansible_facts['distribution'] != 'RedHat' and ansible_facts['distribution'] != 'CentOS') or ansible_facts['distribution_major_version']|int >= 9

- name: Install btrfs-progs
  become: true
  become_method: sudo
  yum:
    update_cache: true
    name: "{{ packages }}"
  retries: 3
  delay: 5
  register: result
  until: result is succeeded
  vars:
    packages:
      - btrfs-progs
  when: ansible_distribution == 'Fedora'

- name: Install dependencies for building xfsprogs
  become: true
  become_flags: "su - -c"
  become_method: sudo
  dnf:
    name: "{{ packages }}"
    enablerepo: "*"
  retries: 3
  delay: 5
  register: result
  until: result is succeeded
  vars:
    packages:
      - inih-devel
      - libedit-devel
      - libicu-devel
      - lvm2-devel
      - userspace-rcu-devel
      - device-mapper-devel
      - device-mapper-event-devel
      - libselinux-devel
      - libsepol-devel
      - pcre2-devel
      - gcc-c++
  when: "fstests_xfs_build_custom_xfsprogs|bool"
