---
- name: Gather os_family
  ansible.builtin.setup:
    gather_subset:
      - "os_family"
  when: ansible_os_family is not defined
  tags: vars_simple

- name: Import optional user secret specific variables
  ansible.builtin.include_vars: "{{ item }}"
  ignore_errors: true
  with_first_found:
    - files:
        - "secret.yml"
      skip: true
  tags: vars

- name: Import optional distribution specific variables
  ansible.builtin.include_vars: "{{ item }}"
  ignore_errors: true
  with_first_found:
    - files:
        - "{{ ansible_facts['os_family'] | lower }}.yml"
      skip: true
  tags: vars

- name: Debian-specific setup
  ansible.builtin.include_tasks: debian/main.yml
  when:
    - ansible_os_family == "Debian"
    - devconfig_try_refresh_repos|bool or devconfig_try_install_kdevtools|bool or kdevops_cli_install|bool
  tags: vars_simple

- name: SuSE-specific setup
  ansible.builtin.include_tasks: suse/main.yml
  when:
    - ansible_os_family == "Suse"
    - devconfig_try_refresh_repos|bool or devconfig_try_install_kdevtools|bool or kdevops_cli_install|bool
  tags: vars_simple

- name: Red Hat-specific setup
  ansible.builtin.include_tasks: redhat/main.yml
  when:
    - ansible_os_family == "RedHat"
    - devconfig_try_refresh_repos|bool or devconfig_try_install_kdevtools|bool or kdevops_cli_install|bool
  tags: vars_simple
