# SPDX-License-Identifier copyleft-next-0.3.1
---
mirror_user_system_dir: "~/.config/systemd/user/"
local_systemd_path: "/usr/local/lib/systemd/system/"

install_linux_mirror: false
# Please keep these in alphabetical order
defaults_blktrace_git: "https://git.kernel.dk/blktrace"
defaults_dbench_git: "https://github.com/linux-kdevops/dbench.git"
defaults_kdevops_results_archive_git: "https://github.com/linux-kdevops/kdevops-results-archive.git"
defaults_git_git: "https://git.kernel.org/pub/scm/git/git.git"
defaults_ltp_git: "https://github.com/linux-test-project/ltp.git"
defaults_mmtests_git: "https://github.com/gormanm/mmtests.git"
defaults_nfstest_git: "git://git.linux-nfs.org/projects/mora/nfstest.git"
defaults_pynfs_git: "git://git.linux-nfs.org/projects/cdmackay/pynfs.git"
defaults_xfsprogs_git: "https://git.kernel.org/pub/scm/fs/xfs/xfsprogs-dev.git"
defaults_xfsdump_git: "https://github.com/linux-kdevops/xfsdump-dev.git"

# These are mirrors which have variability support. The above should be converted
# to these types so to support alternatives for sources and also the ability to
# not use git and instead https in case of firewall restrictions in some
# environments.
mirror_kdevops_url: "https://github.com/linux-kdevops/kdevops.git"
mirror_stable_url: "https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git"
mirror_stable_rc_url: "https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git"
mirror_torvalds_url: "git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git"

install_only_git_daemon: false

linux_mirror_nfs: false
