---
# tasks to install dependencies for selftests on localhost (for 9P builds)
# Uses Kconfig distro variables instead of ansible_facts to detect control host OS
- name: Debian-specific setup for localhost
  ansible.builtin.import_tasks: tasks/install-deps/debian/main.yml
  when: distro_debian_based|bool
- ansible.builtin.import_tasks: tasks/install-deps/suse/main.yml
  when: distro_suse_based|bool
- ansible.builtin.import_tasks: tasks/install-deps/redhat/main.yml
  when: distro_redhat_based|bool
